name: Risk Check

on: [push, pull_request]

jobs:
  risk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Risk Analyzer
        run: |
          pip install -r requirements.txt
          python main.py analyze HEAD
